// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/aikowocki/yandex-go-ext/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockThumbnailRepository is an autogenerated mock type for the ThumbnailRepository type
type MockThumbnailRepository struct {
	mock.Mock
}

type MockThumbnailRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockThumbnailRepository) EXPECT() *MockThumbnailRepository_Expecter {
	return &MockThumbnailRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, thumbnail
func (_m *MockThumbnailRepository) Create(ctx context.Context, thumbnail *domain.Thumbnail) error {
	ret := _m.Called(ctx, thumbnail)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Thumbnail) error); ok {
		r0 = rf(ctx, thumbnail)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockThumbnailRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockThumbnailRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - thumbnail *domain.Thumbnail
func (_e *MockThumbnailRepository_Expecter) Create(ctx interface{}, thumbnail interface{}) *MockThumbnailRepository_Create_Call {
	return &MockThumbnailRepository_Create_Call{Call: _e.mock.On("Create", ctx, thumbnail)}
}

func (_c *MockThumbnailRepository_Create_Call) Run(run func(ctx context.Context, thumbnail *domain.Thumbnail)) *MockThumbnailRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Thumbnail))
	})
	return _c
}

func (_c *MockThumbnailRepository_Create_Call) Return(_a0 error) *MockThumbnailRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockThumbnailRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Thumbnail) error) *MockThumbnailRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByAvatarID provides a mock function with given fields: ctx, avatarID
func (_m *MockThumbnailRepository) DeleteByAvatarID(ctx context.Context, avatarID uuid.UUID) error {
	ret := _m.Called(ctx, avatarID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByAvatarID")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, avatarID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockThumbnailRepository_DeleteByAvatarID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByAvatarID'
type MockThumbnailRepository_DeleteByAvatarID_Call struct {
	*mock.Call
}

// DeleteByAvatarID is a helper method to define mock.On call
//   - ctx context.Context
//   - avatarID uuid.UUID
func (_e *MockThumbnailRepository_Expecter) DeleteByAvatarID(ctx interface{}, avatarID interface{}) *MockThumbnailRepository_DeleteByAvatarID_Call {
	return &MockThumbnailRepository_DeleteByAvatarID_Call{Call: _e.mock.On("DeleteByAvatarID", ctx, avatarID)}
}

func (_c *MockThumbnailRepository_DeleteByAvatarID_Call) Run(run func(ctx context.Context, avatarID uuid.UUID)) *MockThumbnailRepository_DeleteByAvatarID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockThumbnailRepository_DeleteByAvatarID_Call) Return(_a0 error) *MockThumbnailRepository_DeleteByAvatarID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockThumbnailRepository_DeleteByAvatarID_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockThumbnailRepository_DeleteByAvatarID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByAvatarID provides a mock function with given fields: ctx, avatarID
func (_m *MockThumbnailRepository) ListByAvatarID(ctx context.Context, avatarID uuid.UUID) ([]*domain.Thumbnail, error) {
	ret := _m.Called(ctx, avatarID)

	if len(ret) == 0 {
		panic("no return value specified for ListByAvatarID")
	}

	var r0 []*domain.Thumbnail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*domain.Thumbnail, error)); ok {
		return rf(ctx, avatarID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*domain.Thumbnail); ok {
		r0 = rf(ctx, avatarID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Thumbnail)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, avatarID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockThumbnailRepository_ListByAvatarID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByAvatarID'
type MockThumbnailRepository_ListByAvatarID_Call struct {
	*mock.Call
}

// ListByAvatarID is a helper method to define mock.On call
//   - ctx context.Context
//   - avatarID uuid.UUID
func (_e *MockThumbnailRepository_Expecter) ListByAvatarID(ctx interface{}, avatarID interface{}) *MockThumbnailRepository_ListByAvatarID_Call {
	return &MockThumbnailRepository_ListByAvatarID_Call{Call: _e.mock.On("ListByAvatarID", ctx, avatarID)}
}

func (_c *MockThumbnailRepository_ListByAvatarID_Call) Run(run func(ctx context.Context, avatarID uuid.UUID)) *MockThumbnailRepository_ListByAvatarID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockThumbnailRepository_ListByAvatarID_Call) Return(_a0 []*domain.Thumbnail, _a1 error) *MockThumbnailRepository_ListByAvatarID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockThumbnailRepository_ListByAvatarID_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*domain.Thumbnail, error)) *MockThumbnailRepository_ListByAvatarID_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockThumbnailRepository creates a new instance of MockThumbnailRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockThumbnailRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockThumbnailRepository {
	mock := &MockThumbnailRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
