// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	image "image"
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// MockImageProcessor is an autogenerated mock type for the ImageProcessor type
type MockImageProcessor struct {
	mock.Mock
}

type MockImageProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockImageProcessor) EXPECT() *MockImageProcessor_Expecter {
	return &MockImageProcessor_Expecter{mock: &_m.Mock}
}

// CreateThumbnail provides a mock function with given fields: img, width, height
func (_m *MockImageProcessor) CreateThumbnail(img image.Image, width int, height int) image.Image {
	ret := _m.Called(img, width, height)

	if len(ret) == 0 {
		panic("no return value specified for CreateThumbnail")
	}

	var r0 image.Image
	if rf, ok := ret.Get(0).(func(image.Image, int, int) image.Image); ok {
		r0 = rf(img, width, height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(image.Image)
		}
	}

	return r0
}

// MockImageProcessor_CreateThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateThumbnail'
type MockImageProcessor_CreateThumbnail_Call struct {
	*mock.Call
}

// CreateThumbnail is a helper method to define mock.On call
//   - img image.Image
//   - width int
//   - height int
func (_e *MockImageProcessor_Expecter) CreateThumbnail(img interface{}, width interface{}, height interface{}) *MockImageProcessor_CreateThumbnail_Call {
	return &MockImageProcessor_CreateThumbnail_Call{Call: _e.mock.On("CreateThumbnail", img, width, height)}
}

func (_c *MockImageProcessor_CreateThumbnail_Call) Run(run func(img image.Image, width int, height int)) *MockImageProcessor_CreateThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(image.Image), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockImageProcessor_CreateThumbnail_Call) Return(_a0 image.Image) *MockImageProcessor_CreateThumbnail_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageProcessor_CreateThumbnail_Call) RunAndReturn(run func(image.Image, int, int) image.Image) *MockImageProcessor_CreateThumbnail_Call {
	_c.Call.Return(run)
	return _c
}

// Decode provides a mock function with given fields: r
func (_m *MockImageProcessor) Decode(r io.Reader) (image.Image, string, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 image.Image
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(io.Reader) (image.Image, string, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(io.Reader) image.Image); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(image.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(io.Reader) string); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(io.Reader) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockImageProcessor_Decode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Decode'
type MockImageProcessor_Decode_Call struct {
	*mock.Call
}

// Decode is a helper method to define mock.On call
//   - r io.Reader
func (_e *MockImageProcessor_Expecter) Decode(r interface{}) *MockImageProcessor_Decode_Call {
	return &MockImageProcessor_Decode_Call{Call: _e.mock.On("Decode", r)}
}

func (_c *MockImageProcessor_Decode_Call) Run(run func(r io.Reader)) *MockImageProcessor_Decode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Reader))
	})
	return _c
}

func (_c *MockImageProcessor_Decode_Call) Return(_a0 image.Image, _a1 string, _a2 error) *MockImageProcessor_Decode_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockImageProcessor_Decode_Call) RunAndReturn(run func(io.Reader) (image.Image, string, error)) *MockImageProcessor_Decode_Call {
	_c.Call.Return(run)
	return _c
}

// Encode provides a mock function with given fields: w, img, format, quality
func (_m *MockImageProcessor) Encode(w io.Writer, img image.Image, format string, quality int) error {
	ret := _m.Called(w, img, format, quality)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(io.Writer, image.Image, string, int) error); ok {
		r0 = rf(w, img, format, quality)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockImageProcessor_Encode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encode'
type MockImageProcessor_Encode_Call struct {
	*mock.Call
}

// Encode is a helper method to define mock.On call
//   - w io.Writer
//   - img image.Image
//   - format string
//   - quality int
func (_e *MockImageProcessor_Expecter) Encode(w interface{}, img interface{}, format interface{}, quality interface{}) *MockImageProcessor_Encode_Call {
	return &MockImageProcessor_Encode_Call{Call: _e.mock.On("Encode", w, img, format, quality)}
}

func (_c *MockImageProcessor_Encode_Call) Run(run func(w io.Writer, img image.Image, format string, quality int)) *MockImageProcessor_Encode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(io.Writer), args[1].(image.Image), args[2].(string), args[3].(int))
	})
	return _c
}

func (_c *MockImageProcessor_Encode_Call) Return(_a0 error) *MockImageProcessor_Encode_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockImageProcessor_Encode_Call) RunAndReturn(run func(io.Writer, image.Image, string, int) error) *MockImageProcessor_Encode_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateMagicBytes provides a mock function with given fields: data
func (_m *MockImageProcessor) ValidateMagicBytes(data []byte) (string, error) {
	ret := _m.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for ValidateMagicBytes")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func([]byte) (string, error)); ok {
		return rf(data)
	}
	if rf, ok := ret.Get(0).(func([]byte) string); ok {
		r0 = rf(data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockImageProcessor_ValidateMagicBytes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateMagicBytes'
type MockImageProcessor_ValidateMagicBytes_Call struct {
	*mock.Call
}

// ValidateMagicBytes is a helper method to define mock.On call
//   - data []byte
func (_e *MockImageProcessor_Expecter) ValidateMagicBytes(data interface{}) *MockImageProcessor_ValidateMagicBytes_Call {
	return &MockImageProcessor_ValidateMagicBytes_Call{Call: _e.mock.On("ValidateMagicBytes", data)}
}

func (_c *MockImageProcessor_ValidateMagicBytes_Call) Run(run func(data []byte)) *MockImageProcessor_ValidateMagicBytes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockImageProcessor_ValidateMagicBytes_Call) Return(_a0 string, _a1 error) *MockImageProcessor_ValidateMagicBytes_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockImageProcessor_ValidateMagicBytes_Call) RunAndReturn(run func([]byte) (string, error)) *MockImageProcessor_ValidateMagicBytes_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockImageProcessor creates a new instance of MockImageProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockImageProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockImageProcessor {
	mock := &MockImageProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
