// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/aikowocki/yandex-go-ext/internal/domain"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockAvatarRepository is an autogenerated mock type for the AvatarRepository type
type MockAvatarRepository struct {
	mock.Mock
}

type MockAvatarRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAvatarRepository) EXPECT() *MockAvatarRepository_Expecter {
	return &MockAvatarRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, avatar
func (_m *MockAvatarRepository) Create(ctx context.Context, avatar *domain.Avatar) error {
	ret := _m.Called(ctx, avatar)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Avatar) error); ok {
		r0 = rf(ctx, avatar)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAvatarRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAvatarRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - avatar *domain.Avatar
func (_e *MockAvatarRepository_Expecter) Create(ctx interface{}, avatar interface{}) *MockAvatarRepository_Create_Call {
	return &MockAvatarRepository_Create_Call{Call: _e.mock.On("Create", ctx, avatar)}
}

func (_c *MockAvatarRepository_Create_Call) Run(run func(ctx context.Context, avatar *domain.Avatar)) *MockAvatarRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Avatar))
	})
	return _c
}

func (_c *MockAvatarRepository_Create_Call) Return(_a0 error) *MockAvatarRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAvatarRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Avatar) error) *MockAvatarRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAvatarRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAvatarRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAvatarRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAvatarRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAvatarRepository_Delete_Call {
	return &MockAvatarRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAvatarRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAvatarRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAvatarRepository_Delete_Call) Return(_a0 error) *MockAvatarRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAvatarRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockAvatarRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockAvatarRepository) GetByID(ctx context.Context, id uuid.UUID) (*domain.Avatar, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*domain.Avatar, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *domain.Avatar); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAvatarRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockAvatarRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockAvatarRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockAvatarRepository_GetByID_Call {
	return &MockAvatarRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockAvatarRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockAvatarRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockAvatarRepository_GetByID_Call) Return(_a0 *domain.Avatar, _a1 error) *MockAvatarRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAvatarRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*domain.Avatar, error)) *MockAvatarRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByUserID provides a mock function with given fields: ctx, userID
func (_m *MockAvatarRepository) GetByUserID(ctx context.Context, userID string) (*domain.Avatar, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetByUserID")
	}

	var r0 *domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Avatar, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Avatar); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAvatarRepository_GetByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByUserID'
type MockAvatarRepository_GetByUserID_Call struct {
	*mock.Call
}

// GetByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAvatarRepository_Expecter) GetByUserID(ctx interface{}, userID interface{}) *MockAvatarRepository_GetByUserID_Call {
	return &MockAvatarRepository_GetByUserID_Call{Call: _e.mock.On("GetByUserID", ctx, userID)}
}

func (_c *MockAvatarRepository_GetByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockAvatarRepository_GetByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAvatarRepository_GetByUserID_Call) Return(_a0 *domain.Avatar, _a1 error) *MockAvatarRepository_GetByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAvatarRepository_GetByUserID_Call) RunAndReturn(run func(context.Context, string) (*domain.Avatar, error)) *MockAvatarRepository_GetByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPendingForProcessing provides a mock function with given fields: ctx, limit
func (_m *MockAvatarRepository) GetPendingForProcessing(ctx context.Context, limit int) ([]*domain.Avatar, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetPendingForProcessing")
	}

	var r0 []*domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*domain.Avatar, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*domain.Avatar); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAvatarRepository_GetPendingForProcessing_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPendingForProcessing'
type MockAvatarRepository_GetPendingForProcessing_Call struct {
	*mock.Call
}

// GetPendingForProcessing is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockAvatarRepository_Expecter) GetPendingForProcessing(ctx interface{}, limit interface{}) *MockAvatarRepository_GetPendingForProcessing_Call {
	return &MockAvatarRepository_GetPendingForProcessing_Call{Call: _e.mock.On("GetPendingForProcessing", ctx, limit)}
}

func (_c *MockAvatarRepository_GetPendingForProcessing_Call) Run(run func(ctx context.Context, limit int)) *MockAvatarRepository_GetPendingForProcessing_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockAvatarRepository_GetPendingForProcessing_Call) Return(_a0 []*domain.Avatar, _a1 error) *MockAvatarRepository_GetPendingForProcessing_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAvatarRepository_GetPendingForProcessing_Call) RunAndReturn(run func(context.Context, int) ([]*domain.Avatar, error)) *MockAvatarRepository_GetPendingForProcessing_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID, limit, offset
func (_m *MockAvatarRepository) ListByUserID(ctx context.Context, userID string, limit int, offset int) ([]*domain.Avatar, error) {
	ret := _m.Called(ctx, userID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*domain.Avatar
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*domain.Avatar, error)); ok {
		return rf(ctx, userID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*domain.Avatar); ok {
		r0 = rf(ctx, userID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Avatar)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAvatarRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockAvatarRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - limit int
//   - offset int
func (_e *MockAvatarRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}, limit interface{}, offset interface{}) *MockAvatarRepository_ListByUserID_Call {
	return &MockAvatarRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID, limit, offset)}
}

func (_c *MockAvatarRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID string, limit int, offset int)) *MockAvatarRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockAvatarRepository_ListByUserID_Call) Return(_a0 []*domain.Avatar, _a1 error) *MockAvatarRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAvatarRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, string, int, int) ([]*domain.Avatar, error)) *MockAvatarRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, avatar
func (_m *MockAvatarRepository) Update(ctx context.Context, avatar *domain.Avatar) error {
	ret := _m.Called(ctx, avatar)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Avatar) error); ok {
		r0 = rf(ctx, avatar)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAvatarRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAvatarRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - avatar *domain.Avatar
func (_e *MockAvatarRepository_Expecter) Update(ctx interface{}, avatar interface{}) *MockAvatarRepository_Update_Call {
	return &MockAvatarRepository_Update_Call{Call: _e.mock.On("Update", ctx, avatar)}
}

func (_c *MockAvatarRepository_Update_Call) Run(run func(ctx context.Context, avatar *domain.Avatar)) *MockAvatarRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Avatar))
	})
	return _c
}

func (_c *MockAvatarRepository_Update_Call) Return(_a0 error) *MockAvatarRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAvatarRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Avatar) error) *MockAvatarRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProcessingStatus provides a mock function with given fields: ctx, id, status
func (_m *MockAvatarRepository) UpdateProcessingStatus(ctx context.Context, id uuid.UUID, status domain.ProcessingStatus) error {
	ret := _m.Called(ctx, id, status)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProcessingStatus")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, domain.ProcessingStatus) error); ok {
		r0 = rf(ctx, id, status)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAvatarRepository_UpdateProcessingStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProcessingStatus'
type MockAvatarRepository_UpdateProcessingStatus_Call struct {
	*mock.Call
}

// UpdateProcessingStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - status domain.ProcessingStatus
func (_e *MockAvatarRepository_Expecter) UpdateProcessingStatus(ctx interface{}, id interface{}, status interface{}) *MockAvatarRepository_UpdateProcessingStatus_Call {
	return &MockAvatarRepository_UpdateProcessingStatus_Call{Call: _e.mock.On("UpdateProcessingStatus", ctx, id, status)}
}

func (_c *MockAvatarRepository_UpdateProcessingStatus_Call) Run(run func(ctx context.Context, id uuid.UUID, status domain.ProcessingStatus)) *MockAvatarRepository_UpdateProcessingStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(domain.ProcessingStatus))
	})
	return _c
}

func (_c *MockAvatarRepository_UpdateProcessingStatus_Call) Return(_a0 error) *MockAvatarRepository_UpdateProcessingStatus_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAvatarRepository_UpdateProcessingStatus_Call) RunAndReturn(run func(context.Context, uuid.UUID, domain.ProcessingStatus) error) *MockAvatarRepository_UpdateProcessingStatus_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAvatarRepository creates a new instance of MockAvatarRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAvatarRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAvatarRepository {
	mock := &MockAvatarRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
