// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	contracts "github.com/aikowocki/yandex-go-ext/internal/contracts"
	mock "github.com/stretchr/testify/mock"
)

// MockMessageBroker is an autogenerated mock type for the MessageBroker type
type MockMessageBroker struct {
	mock.Mock
}

type MockMessageBroker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageBroker) EXPECT() *MockMessageBroker_Expecter {
	return &MockMessageBroker_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockMessageBroker) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageBroker_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockMessageBroker_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockMessageBroker_Expecter) Close() *MockMessageBroker_Close_Call {
	return &MockMessageBroker_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockMessageBroker_Close_Call) Run(run func()) *MockMessageBroker_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessageBroker_Close_Call) Return(_a0 error) *MockMessageBroker_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageBroker_Close_Call) RunAndReturn(run func() error) *MockMessageBroker_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, topic, msg
func (_m *MockMessageBroker) Publish(ctx context.Context, topic string, msg *contracts.Message) error {
	ret := _m.Called(ctx, topic, msg)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *contracts.Message) error); ok {
		r0 = rf(ctx, topic, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageBroker_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockMessageBroker_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - msg *contracts.Message
func (_e *MockMessageBroker_Expecter) Publish(ctx interface{}, topic interface{}, msg interface{}) *MockMessageBroker_Publish_Call {
	return &MockMessageBroker_Publish_Call{Call: _e.mock.On("Publish", ctx, topic, msg)}
}

func (_c *MockMessageBroker_Publish_Call) Run(run func(ctx context.Context, topic string, msg *contracts.Message)) *MockMessageBroker_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(*contracts.Message))
	})
	return _c
}

func (_c *MockMessageBroker_Publish_Call) Return(_a0 error) *MockMessageBroker_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageBroker_Publish_Call) RunAndReturn(run func(context.Context, string, *contracts.Message) error) *MockMessageBroker_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, topic, handler
func (_m *MockMessageBroker) Subscribe(ctx context.Context, topic string, handler contracts.MessageHandler) error {
	ret := _m.Called(ctx, topic, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, contracts.MessageHandler) error); ok {
		r0 = rf(ctx, topic, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageBroker_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockMessageBroker_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - handler contracts.MessageHandler
func (_e *MockMessageBroker_Expecter) Subscribe(ctx interface{}, topic interface{}, handler interface{}) *MockMessageBroker_Subscribe_Call {
	return &MockMessageBroker_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, topic, handler)}
}

func (_c *MockMessageBroker_Subscribe_Call) Run(run func(ctx context.Context, topic string, handler contracts.MessageHandler)) *MockMessageBroker_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(contracts.MessageHandler))
	})
	return _c
}

func (_c *MockMessageBroker_Subscribe_Call) Return(_a0 error) *MockMessageBroker_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageBroker_Subscribe_Call) RunAndReturn(run func(context.Context, string, contracts.MessageHandler) error) *MockMessageBroker_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageBroker creates a new instance of MockMessageBroker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageBroker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageBroker {
	mock := &MockMessageBroker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
