// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	contracts "github.com/aikowocki/yandex-go-ext/internal/contracts"
	mock "github.com/stretchr/testify/mock"
)

// MockConsumer is an autogenerated mock type for the Consumer type
type MockConsumer struct {
	mock.Mock
}

type MockConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumer) EXPECT() *MockConsumer_Expecter {
	return &MockConsumer_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function with given fields: ctx, topic, handler
func (_m *MockConsumer) Subscribe(ctx context.Context, topic string, handler contracts.MessageHandler) error {
	ret := _m.Called(ctx, topic, handler)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, contracts.MessageHandler) error); ok {
		r0 = rf(ctx, topic, handler)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConsumer_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockConsumer_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - handler contracts.MessageHandler
func (_e *MockConsumer_Expecter) Subscribe(ctx interface{}, topic interface{}, handler interface{}) *MockConsumer_Subscribe_Call {
	return &MockConsumer_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, topic, handler)}
}

func (_c *MockConsumer_Subscribe_Call) Run(run func(ctx context.Context, topic string, handler contracts.MessageHandler)) *MockConsumer_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(contracts.MessageHandler))
	})
	return _c
}

func (_c *MockConsumer_Subscribe_Call) Return(_a0 error) *MockConsumer_Subscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumer_Subscribe_Call) RunAndReturn(run func(context.Context, string, contracts.MessageHandler) error) *MockConsumer_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConsumer creates a new instance of MockConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumer {
	mock := &MockConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
