version: '3'

includes:
  go:
    taskfile: tasks/Taskfile.go.yaml
    flatten: true
  docker:
    taskfile: tasks/Taskfile.docker.yaml
    flatten: true
  k8s:
    taskfile: tasks/Taskfile.k8s.yaml
    flatten: true
  quality:
    taskfile: tasks/Taskfile.quality.yaml
    flatten: true
