apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pyroscope.fullname" . }}
  labels:
    {{- include "pyroscope.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pyroscope.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pyroscope.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
          - -config.file=/etc/pyroscope/pyroscope.yaml
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 5
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/pyroscope
          readOnly: true
        - name: storage
          mountPath: {{ .Values.persistence.mountPath }}
      volumes:
      - name: config
        configMap:
          name: {{ include "pyroscope.fullname" . }}
      - name: storage
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "pyroscope.fullname" . }}
        {{- else }}
        emptyDir: {}
        {{- end }}
