image:
  repository: apache/kafka
  tag: "4.0.0"
  pullPolicy: IfNotPresent
storageClass: local-path
storageSize: 5Gi
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: "1"
    memory: 1Gi
topics:
  - avatar.uploaded
  - avatar.deleted
  - avatar.uploaded.dlq
  - avatar.deleted.dlq
