apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels: {app.kubernetes.io/name: jaeger}
spec:
  selector: {app.kubernetes.io/name: jaeger}
  ports:
    - {name: query, port: 16686, targetPort: query}
    - {name: otlp-grpc, port: 4317, targetPort: otlp-grpc}
    - {name: otlp-http, port: 4318, targetPort: otlp-http}
