{{- if .Values.secrets.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "gophprofile.fullname" . }}-secrets
  labels: {{- include "gophprofile.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secrets.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ include "gophprofile.fullname" . }}-secrets
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef: {key: {{ .Values.secrets.externalSecret.remoteKey }}, property: DATABASE_URL}
    - secretKey: S3_ENDPOINT
      remoteRef: {key: {{ .Values.secrets.externalSecret.remoteKey }}, property: S3_ENDPOINT}
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef: {key: {{ .Values.secrets.externalSecret.remoteKey }}, property: S3_ACCESS_KEY_ID}
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef: {key: {{ .Values.secrets.externalSecret.remoteKey }}, property: S3_SECRET_ACCESS_KEY}
    - secretKey: KAFKA_BROKERS
      remoteRef: {key: {{ .Values.secrets.externalSecret.remoteKey }}, property: KAFKA_BROKERS}
    - secretKey: OTEL_EXPORTER_OTLP_ENDPOINT
      remoteRef: {key: {{ .Values.secrets.externalSecret.remoteKey }}, property: OTEL_EXPORTER_OTLP_ENDPOINT}
    - secretKey: PYROSCOPE_SERVER_ADDRESS
      remoteRef: {key: {{ .Values.secrets.externalSecret.remoteKey }}, property: PYROSCOPE_SERVER_ADDRESS}
    - secretKey: PYROSCOPE_AUTH_TOKEN
      remoteRef: {key: {{ .Values.secrets.externalSecret.remoteKey }}, property: PYROSCOPE_AUTH_TOKEN}
{{- end }}
