{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gophprofile.fullname" . }}-default-deny
  labels: {{- include "gophprofile.labels" . | nindent 4 }}
spec:
  podSelector: {}
  policyTypes: [Ingress, Egress]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "gophprofile.fullname" . }}-allow
  labels: {{- include "gophprofile.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gophprofile.name" . }}
  policyTypes: [Ingress, Egress]
  ingress:
    - ports: [{protocol: TCP, port: 8080}]
      from:
        - namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: kube-system}}
        - namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: monitoring}}
  egress:
    - to:
        - namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: kube-system}}
          podSelector: {matchLabels: {k8s-app: kube-dns}}
      ports:
        - {protocol: UDP, port: 53}
        - {protocol: TCP, port: 53}
    - to: [{namespaceSelector: {matchLabels: {kubernetes.io/metadata.name: gophprofile-deps}}}]
      ports:
        - {protocol: TCP, port: 5432}
        - {protocol: TCP, port: 9000}
        - {protocol: TCP, port: 9092}
        - {protocol: TCP, port: 4040}
        - {protocol: TCP, port: 4317}
        - {protocol: TCP, port: 4318}
{{- end }}
