apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gophprofile.fullname" . }}-server
  labels: {{- include "gophprofile.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "gophprofile.selector" . | nindent 6 }}
      app.kubernetes.io/component: server
