{{- if not .Values.secrets.externalSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.fullname" . }}-secrets
  labels: {{- include "gophprofile.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "secrets.databaseURL is required" .Values.secrets.databaseURL | quote }}
  S3_ENDPOINT: {{ required "secrets.s3Endpoint is required" .Values.secrets.s3Endpoint | quote }}
  S3_ACCESS_KEY_ID: {{ required "secrets.s3AccessKeyID is required" .Values.secrets.s3AccessKeyID | quote }}
  S3_SECRET_ACCESS_KEY: {{ required "secrets.s3SecretAccessKey is required" .Values.secrets.s3SecretAccessKey | quote }}
  KAFKA_BROKERS: {{ required "secrets.kafkaBrokers is required" .Values.secrets.kafkaBrokers | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ required "secrets.otelEndpoint is required" .Values.secrets.otelEndpoint | quote }}
  PYROSCOPE_SERVER_ADDRESS: {{ .Values.secrets.pyroscopeServerAddress | quote }}
  PYROSCOPE_AUTH_TOKEN: {{ .Values.secrets.pyroscopeAuthToken | quote }}
{{- end }}
