// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Поддержка API",
            "email": "support@gophprofile.local"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/avatars": {
            "post": {
                "description": "Загрузка файла изображения для создания нового аватара. Требует multipart/form-data с файлом и опциональными параметрами обрезки.",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Аватары"
                ],
                "summary": "Создание нового аватара",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя (обязателен)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "Файл изображения (JPEG, PNG, WebP)",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Координата X обрезки (0.0-1.0)",
                        "name": "crop_x",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Координата Y обрезки (0.0-1.0)",
                        "name": "crop_y",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Размер обрезки (0.0-1.0)",
                        "name": "crop_size",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.UploadResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный ввод или неподдерживаемый формат файла",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Аватар уже существует",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    },
                    "413": {
                        "description": "Файл слишком большой (превышает 10МБ)",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/avatars/{id}": {
            "get": {
                "description": "Скачивает аватар в оригинальном или уменьшенном размере. Возвращает бинарный поток с соответствующим Content-Type.",
                "produces": [
                    "image/jpeg",
                    "image/png",
                    "image/webp"
                ],
                "tags": [
                    "Аватары"
                ],
                "summary": "Скачивание изображения аватара",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID аватара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Размер изображения: original, 100x100, или 300x300 (по умолчанию: original)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Бинарные данные изображения аватара",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Некорректный UUID или параметр размера",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Аватар или миниатюра не найдены",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет конкретный аватар. Только владелец может удалять свой аватар.",
                "tags": [
                    "Аватары"
                ],
                "summary": "Удаление аватара",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя (должен совпадать с владельцем)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "UUID аватара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Аватар успешно удалён"
                    },
                    "400": {
                        "description": "Некорректный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Пользователь не является владельцем аватара",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Аватар не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/avatars/{id}/crop": {
            "patch": {
                "description": "Обновляет координаты обрезки существующего аватара. Только владелец может обновлять свой аватар.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Аватары"
                ],
                "summary": "Обновление параметров обрезки аватара",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя (должен совпадать с владельцем)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "UUID аватара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Параметры обрезки",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.AvatarResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный ввод или отсутствующие параметры",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Пользователь не является владельцем аватара",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Аватар не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/avatars/{id}/metadata": {
            "get": {
                "description": "Получает метаданные конкретного аватара, включая миниатюры с временными ссылками (действительны 15 минут).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Аватары"
                ],
                "summary": "Получение метаданных аватара",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID аватара",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.AvatarResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный формат UUID",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Аватар не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{user_id}/avatar": {
            "get": {
                "description": "Скачивает активный аватар конкретного пользователя. Возвращает бинарный поток изображения.",
                "produces": [
                    "image/jpeg",
                    "image/png",
                    "image/webp"
                ],
                "tags": [
                    "Аватары"
                ],
                "summary": "Скачивание текущего аватара пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Размер изображения: original, 100x100, или 300x300 (по умолчанию: original)",
                        "name": "size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Бинарные данные аватара пользователя",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Некорректный ввод",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "У пользователя нет активного аватара",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Удаляет активный аватар пользователя. ID пользователя в пути должен совпадать с заголовком X-User-ID.",
                "tags": [
                    "Аватары"
                ],
                "summary": "Удаление текущего аватара пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя (должен совпадать с path user_id)",
                        "name": "X-User-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Аватар пользователя успешно удалён"
                    },
                    "400": {
                        "description": "Некорректный ввод",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Несовпадение ID пользователя или пользователь не владелец",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "У пользователя нет активного аватара",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/users/{user_id}/avatars": {
            "get": {
                "description": "Получает постраничный список всех аватаров конкретного пользователя.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Аватары"
                ],
                "summary": "Получение списка аватаров пользователя",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Идентификатор пользователя",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Элементов на странице (1-100, по умолчанию: 20)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Смещение для постраничности (по умолчанию: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Список аватаров с информацией о постраничности",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ListAvatarsResponse"
                        }
                    },
                    "400": {
                        "description": "Некорректный ввод",
                        "schema": {
                            "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Проверяет, готова ли служба обрабатывать трафик. Включает проверку внешних зависимостей (БД, хранилище, брокер).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Healthcheck"
                ],
                "summary": "Проверка готовности (readiness probe)",
                "responses": {
                    "200": {
                        "description": "Служба готова",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Служба не готова (зависимость нездорова)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/livez": {
            "get": {
                "description": "Проверяет, что HTTP процесс сервера живой. Не проверяет внешние зависимости.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Healthcheck"
                ],
                "summary": "Проверка живого процесса (liveness probe)",
                "responses": {
                    "200": {
                        "description": "Сервер живой",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "description": "Проверяет, готова ли служба обрабатывать трафик. Включает проверку внешних зависимостей (БД, хранилище, брокер).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Healthcheck"
                ],
                "summary": "Проверка готовности (readiness probe)",
                "responses": {
                    "200": {
                        "description": "Служба готова",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Служба не готова (зависимость нездорова)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.AvatarResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "crop": {
                    "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.CropResponse"
                },
                "dimensions": {
                    "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.DimensionsResponse"
                },
                "file_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "mime_type": {
                    "type": "string"
                },
                "size": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "thumbnails": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ThumbnailResponse"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.CropResponse": {
            "type": "object",
            "properties": {
                "size": {
                    "type": "number"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.DimensionsResponse": {
            "type": "object",
            "properties": {
                "height": {
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "string"
                },
                "error": {
                    "type": "string"
                },
                "max_size": {
                    "type": "integer"
                }
            }
        },
        "github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ListAvatarsResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.AvatarResponse"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                }
            }
        },
        "github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.ThumbnailResponse": {
            "type": "object",
            "properties": {
                "size": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "github_com_aikowocki_yandex-go-ext_internal_transport_rest_dto.UploadResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "X-User-ID": {
            "description": "Заголовок идентификатора пользователя (обязателен для операций записи)",
            "type": "apiKey",
            "name": "X-User-ID",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "GophProfile API",
	Description:      "Сервис управления аватарами с асинхронной обработкой, S3 хранилищем и развёртыванием в Kubernetes",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
